/*
 * Frame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import com.util.*;

/**
 * @since   2016.5.7
 * @author  Jerry Wang
 */
public class Frame extends javax.swing.JFrame {

	/**
	 * 生成序列化ID
	 */
	private static final long serialVersionUID = 1636988489265952004L;

	/** Creates new form Frame */
	public Frame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jMenu1.setText("\u8bfb\u53d6\u6570\u636e\u96c6\u6587\u4ef6");

		jMenuItem1.setText("\u6253\u5f00");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenu1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem3.setText("\u5bfc\u5165\u6570\u636e\u5e93");
		jMenu1.add(jMenuItem3);

		jMenuItem2.setText("\u5bfc\u51fa");
		jMenu1.add(jMenuItem2);

		jMenuItem4.setText("\u5bfc\u51fa\u6570\u636e\u5e93");
		jMenu1.add(jMenuItem4);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u9000\u51fa");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//打开文件并读入text 
	private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here
		FileDialog fileDialog;
		//An abstract representation of file and directory pathnames. 
		File file = null;
		Frame frame = null;
		fileDialog = new FileDialog(frame, "打开", FileDialog.LOAD);
		fileDialog.setVisible(true);

		try {
			//将textarea清空
			jTextArea1.setText("");
			file = new File(fileDialog.getDirectory(), fileDialog.getFile());
			
			String fileName = file.getName();
		    String prefix = fileName.substring(fileName.lastIndexOf(".") + 1);
		    System.out.println(prefix);
		    
		    //Excel excel = new Excel();
		    //excel.excute();
		    //ReadExcelTest excelTest = new ReadExcelTest();
		    //excelTest.readExcel("D:\\data1.xlsx");
		    
			if( !"xlsx".equals(prefix)) {
				FileReader filereader = new FileReader(file);
				BufferedReader bufferreader = new BufferedReader(filereader);
				String aline;
				while ((aline = bufferreader.readLine()) != null)
					jTextArea1.append(aline + "\n");
				filereader.close();
				bufferreader.close();
			} else {
				ReadExcelTest excelTest = new ReadExcelTest(jTextArea1, file.getAbsolutePath());
			    excelTest.readExcel();
			}
			
		} catch (IOException e) {
			System.out.println(e);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}